# Generated by Django 4.1.7 on 2023-04-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='products')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('available', models.IntegerField()),
            ],
        ),
    ]
