# Generated by Django 4.1.7 on 2023-07-02 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='shirt')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bodycon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='shirt')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Croptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='shirt')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='footwear')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='shirt')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='shoe')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='shoe')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='shirt')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=60)),
                ('fav', models.CharField(max_length=60)),
                ('feedback', models.CharField(max_length=60)),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
